  
comment: "Please refer to our issue template. ☺"
issueConfigs:
- content:
  - "Describe the bug"
  - "Expected behavior"
- content:
  - "Is your feature request related to a problem? Please describe."
  - "Describe the solution you'd like"
  - "Describe alternatives you've considered"
  - "Additional context"
label: "closed by bot"
exception:
  - "helloqiu"
  - "whtsky"
